[Controller] Fix initial script for bluetooth bring up issue.

diff --git a/module/controller/openwrt/ezmesh_ble.init.in b/module/controller/openwrt/ezmesh_ble.init.in
--- a/module/controller/openwrt/ezmesh_ble.init.in
+++ b/module/controller/openwrt/ezmesh_ble.init.in
@@ -4,11 +4,56 @@ START=96
 
 USE_PROCD=1
 
-start_service()
-{
-    procd_open_instance
-    procd_set_param command /usr/bin/ez-bluetooth /tmp/pts_hci
+prog=/usr/bin/ez-bluetooth
+pid=/var/run/ez-bluetooth.pid
+log=/tmp/ez-bluetooth.log
+
+start_service() {
+    procd_open_instance "ez-bluetooth"
+    procd_set_param command sh -c "cd /tmp&&${prog}"
     procd_set_param respawn
-    procd_set_param pidfile /var/run/ez-bluetooth.pid        
+    procd_set_param stdout 1
+    procd_set_param stderr 1
+    procd_set_param pidfile ${pid}
     procd_close_instance
+}
+
+service_started() {
+    echo "Wait $(uptime)" >>${log}
+    sleep 1
+    _count=0
+    while [ ! -h /tmp/pts_hci ]; do
+        sleep 1
+        _count=$((_count + 1))
+        echo "${_count} $(uptime)" >>${log}
+        if [ "30" = "${_count}" ]; then
+            break
+        fi
+    done
+    if [ -h /tmp/pts_hci ]; then
+        echo "attach -- /tmp/pts_hci $(uptime)" >>${log}
+        /usr/bin/hciattach /tmp/pts_hci any
+        _err=$?
+        echo "attach -- A ${_err}, $(uptime)" >>${log}
+        hciconfig hci0 up
+        _err=$?
+        echo "attach -- B ${_err}, $(uptime)" >>${log}
+        kill -9 $(pidof hciattach) ### peter add to fix cpcd stop hold
+        _err=$?
+        echo "attach -- C ${_err}, $(uptime)" >>${log}
+
+    else
+        echo "attach -- err not found /tmp/pts_hci $(uptime)" >>${log}
+    fi
+
+    # sleep 1
+    hciconfig hci0 down
+    sleep 1
+    hciconfig hci0 up
+    # sleep 1
+}
+service_stopped() {
+    hciconfig hci0 down >/dev/null 2>&1
+    kill -9 $(pidof hciattach)
+    rm -f /tmp/pts_hci 2>/dev/null
 }
